// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhtbgjgbtlhuxsibsthp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodGJnamdidGxodXhzaWJzdGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjE0NDYsImV4cCI6MjA3NDQ5NzQ0Nn0.DKxCNR34Oie68qIEtmJwzYep-ur2NmsdmyO7GXdFAMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});